### ISSUE TITLE
DEVICE script to acquire location and write to database

### ISSUE THREAD

**Issue by vr00n** [vr00n/Bus-Lambda#10]
A script to acquire device's current location using `locate_magic.sh` and write to postgres database.

`mac-id,timestamp,location`

@Elixeus need you to provide pyscopg2 connection string and simple python code to write to the database that you have created.

**Comment by aaron-15** [comment]
Hi @Elixeus,
Need all privileges on the master user, currently we cannot insert data into the table.

Could you please grant all privileges the the master user?

**Comment by Elixeus** [comment]
@vr00n @aaron-15  granted access permission and the script above now works properly.

**Comment by aaron-15** [comment]
Loaded 11224 rows into the db.
The database is only 15 MBs. Bus line 100 and 103 have a single day worth of data.

Need to increase database size to acc at least 500 k rows to accommodate all Brooklyn bus lines.

**Comment by vr00n** [comment]
Thanks! @Elixeus can you document what permissions you needed to add to resolve this?

**Comment by Elixeus** [comment]
I granted `select`, `insert`, `update` and `delete` privileges on this table to the user.
